name: CI - LangChain Backend

on:
  pull_request:
    paths:
      - 'mellea_contribs/langchain_backend/**'
      - '.github/workflows/ci-langchain-backend.yml'
      - '.github/workflows/quality-generic.yml'
  push:
    branches:
      - main
    paths:
      - 'mellea_contribs/langchain_backend/**'
      - '.github/workflows/ci-langchain-backend.yml'
      - '.github/workflows/quality-generic.yml'

jobs:
  test:
    uses: ./.github/workflows/quality-generic.yml
    with:
      subpackage: mellea_contribs/langchain_backend
      timeout_minutes: 90

