name: CI - Mellea Integration Core

on:
  pull_request:
    paths:
      - 'mellea_contribs/mellea-integration-core/**'
      - '.github/workflows/ci-mellea-integration-core.yml'
      - '.github/workflows/quality-generic.yml'
  push:
    branches:
      - main
    paths:
      - 'mellea_contribs/mellea-integration-core/**'
      - '.github/workflows/ci-mellea-integration-core.yml'
      - '.github/workflows/quality-generic.yml'

jobs:
  test:
    uses: ./.github/workflows/quality-generic.yml
    with:
      subpackage: mellea_contribs/mellea-integration-core
      skip_ollama: true

