name: "Run CI"

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  mellea-integration-core:
    uses: ./.github/workflows/quality-mellea-integration-core.yml
  
  crewai-backend:
    uses: ./.github/workflows/quality-crewai-backend.yml
    needs: mellea-integration-core
  
  dspy-backend:
    uses: ./.github/workflows/quality-dspy-backend.yml
    needs: mellea-integration-core
  
  langchain-backend:
    uses: ./.github/workflows/quality-langchain-backend.yml
    needs: mellea-integration-core
  
  reqlib-package:
    uses: ./.github/workflows/quality-reqlib-package.yml
  
  tools-package:
    uses: ./.github/workflows/quality-tools-package.yml
